---
- name: Atualiza pacotes e instala pacotes essenciais em distribuições Debian e CentOS
  hosts: all
  become: true
  vars:
    common_packages_debian:
      - git
      - curl
      - zabbix-agent
      - tar
      - gzip
      - htop
      - wget
      - tree
      - vim
      - nano
    common_packages_centos:
      - git
      - curl
      - zabbix-agent
      - tar
      - gzip
      - htop
      - wget
      - tree
      - vim
      - nano
    user_password: "senha_segura"
  tasks:
  - name: Update e Upgrade em distribuições Debian
    when: ansible_os_family == "Debian"
    apt:
      update_cache: yes
      upgrade: dist
  - name: Update e Upgrade em distribuições CentOS
    when: ansible_os_family == "RedHat"
    yum:
      name: '*'
      state: latest
      exclude: kernel*
  - name: Instalação de pacotes em distribuições Debian
    when: ansible_os_family == "Debian"
    apt:
      name: "{{ common_packages_debian }}"
      state: present
  - name: Instalação de pacotes em distribuições CentOS
    when: ansible_os_family == "RedHat"
    yum:
      name: "{{ common_packages_centos }}"
      state: present
  - name: Criação de usuário padrão
    user:
      name: infra
      shell: /bin/bash
      groups: sudo
      password: "{{ user_password | password_hash('sha512') }}"